import Foundation

struct AccountIdentityResolver {
    static func resolvedName(
        tool: ToolKind,
        provider: any Provider,
        inputName: String,
        secret: String
    ) -> String {
        let detectedName = provider.suggestAccountName(from: secret) ?? extractEmail(from: secret)
        if let detectedName,
           inputName.isEmpty || looksAutoGeneratedName(inputName, tool: tool) {
            return detectedName
        }

        if !inputName.isEmpty {
            return inputName
        }

        return "\(tool.displayName) 账号"
    }

    static func looksAutoGeneratedName(_ name: String, tool: ToolKind) -> Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return true }

        let lower = trimmed.lowercased()
        let prefix = tool.displayName.lowercased()
        if tool == .claudeCode,
           lower.range(of: #"^claude [0-9a-f]{8}$"#, options: .regularExpression) != nil {
            return true
        }
        if lower == prefix || lower == "\(prefix)账号" || lower.hasPrefix("\(prefix)-") {
            return true
        }

        if trimmed.contains(":"), trimmed.rangeOfCharacter(from: .decimalDigits) != nil, lower.hasPrefix(prefix) {
            return true
        }

        return false
    }

    static func extractEmail(from text: String) -> String? {
        let pattern = #"[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}"#
        guard let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) else {
            return nil
        }

        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        guard let match = regex.firstMatch(in: text, options: [], range: range),
              let matchRange = Range(match.range, in: text) else {
            return nil
        }

        return String(text[matchRange]).lowercased()
    }

    static func normalizeIdentityName(_ name: String) -> String {
        name.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}
