import Foundation
import Testing
@testable import QuotaBarApp

@Suite("Account identity resolver")
struct AccountIdentityResolverTests {
    @Test("detected provider name replaces empty or generated input")
    func detectedProviderNameReplacesGeneratedInput() {
        let provider = SuggestedNameProvider(name: "dev@example.com")

        #expect(
            AccountIdentityResolver.resolvedName(
                tool: .codex,
                provider: provider,
                inputName: "",
                secret: "secret"
            ) == "dev@example.com"
        )
        #expect(
            AccountIdentityResolver.resolvedName(
                tool: .codex,
                provider: provider,
                inputName: "Codex-123",
                secret: "secret"
            ) == "dev@example.com"
        )
    }

    @Test("manual input is preserved over detected provider name")
    func manualInputIsPreserved() {
        let provider = SuggestedNameProvider(name: "dev@example.com")

        #expect(
            AccountIdentityResolver.resolvedName(
                tool: .cursor,
                provider: provider,
                inputName: "Work laptop",
                secret: "secret"
            ) == "Work laptop"
        )
    }

    @Test("email extraction lowercases first address")
    func emailExtractionLowercasesFirstAddress() {
        #expect(AccountIdentityResolver.extractEmail(from: #"{"email":"DEV@EXAMPLE.COM"}"#) == "dev@example.com")
    }

    @Test("generated name detection covers provider placeholders")
    func generatedNameDetection() {
        #expect(AccountIdentityResolver.looksAutoGeneratedName("", tool: .codex))
        #expect(AccountIdentityResolver.looksAutoGeneratedName("Claude deadbeef", tool: .claudeCode))
        #expect(AccountIdentityResolver.looksAutoGeneratedName("Cursor: 123", tool: .cursor))
        #expect(!AccountIdentityResolver.looksAutoGeneratedName("Production", tool: .codex))
    }
}

private struct SuggestedNameProvider: Provider {
    let name: String?

    var tool: ToolKind { .codex }

    func importCurrentCredentials() async throws -> String {
        throw ProviderError.invalidCredentials
    }

    func activate(account: Account, secret: String) async throws {
        _ = account
        _ = secret
    }

    func fetchQuota(secret: String) async throws -> QuotaSnapshot {
        _ = secret
        throw ProviderError.invalidCredentials
    }

    func suggestAccountName(from secret: String) -> String? {
        _ = secret
        return name
    }
}
